# Constants for kernel dilation
KERNEL_DILATION_1 = 15
KERNEL_DILATION_2 = 21

# Batch size and image dimensions
BATCH_SIZE = 16
HEIGHT = 256
WIDTH = 256

# Configuration options
WEIGHTED_COEFF_MAIN_LOSS = 0.90
WEIGHTED_COEFF_AUX_LOSS = 1 - WEIGHTED_COEFF_MAIN_LOSS

# Default values
DEFAULT_KERNEL_DILATION_1 = 15
DEFAULT_KERNEL_DILATION_2 = 25
DEFAULT_BATCH_SIZE = 16
DEFAULT_NUM_EPOCHS = 100
DEFAULT_LR = 0.01